<p>Condiciones de Uso del Servicio de WiFi gratuito</p>
<p>1/ <strong>Aceptación de las Condiciones de Uso:</strong> Al utilizar el servicio de WiFi gratuito de la red Aceko-FreeWiFi (&quot;el Servicio&quot;), usted acepta cumplir con estas Condiciones de Uso. Si no está de acuerdo con estas Condiciones de Uso, no utilice el Servicio.</p>
<p>2/ <strong>Proveedor del Servicio:</strong> El Servicio es proporcionado por Acerko Telecom (&quot;el Proveedor&quot;). El Proveedor es un operador de telecomunicaciones registrado en España.</p>
<p>3/ <strong>Sin garantías:</strong> El Servicio se proporciona &quot;tal cual&quot; y &quot;según disponibilidad&quot;. El Proveedor no garantiza que el Servicio estará libre de errores, interrupciones, o que satisfará sus necesidades específicas. El Proveedor no se hace responsable de la pérdida de datos, daños a equipos o cualquier otra pérdida o daño que pueda resultar del uso del Servicio.</p>
<p>4/ <strong>Uso legítimo y legal:</strong> Usted se compromete a utilizar el Servicio únicamente con fines legales y legítimos. Queda prohibido el acceso a contenido ilegal, la realización de actividades ilegales o la violación de los derechos de terceros a través del Servicio.</p>
<p>5/ <strong>Seguridad y Privacidad:</strong> El Servicio se proporciona en una red abierta y no cifra el tráfico. Usted es responsable de la seguridad de sus dispositivos y la información que transmite a través del Servicio. El Proveedor no se hace responsable de cualquier acceso no autorizado, interceptación, pérdida o divulgación de información.</p>
<p>6/ <strong>Recopilación de Datos por Terceros:</strong> El Proveedor no recopila datos personales de los usuarios del Servicio. Sin embargo, para garantizar un ambiente seguro y prevenir el acceso a contenido ilegal o inapropiado, utilizamos el servicio Cloudflare DNS 1.1.1.1 for Families para filtrar el contenido accesible a través del Servicio. Cloudflare puede recopilar y procesar datos personales como parte de su servicio. Consulte la Política de Privacidad de Cloudflare en <a href="https://www.cloudflare.com/privacypolicy/">https://www.cloudflare.com/privacypolicy/</a> para más información.</p>
<p>7/ <strong>Restricciones de uso:</strong> El Proveedor se reserva el derecho de establecer límites en el uso del Servicio, como limitaciones de tiempo, velocidad de conexión y ancho de banda. El Proveedor también puede bloquear el acceso a ciertos sitios web o servicios para garantizar el buen funcionamiento del Servicio y cumplir con las leyes aplicables.</p>
<p>8/ <strong>Modificación de las Condiciones de Uso:</strong> El Proveedor se reserva el derecho de modificar estas Condiciones de Uso en cualquier momento. Usted es responsable de revisar y cumplir con las Condiciones de Uso actualizadas cada vez que utilice el Servicio.</p>
<p>9/ <strong>Terminación del Servicio:</strong> El Proveedor se reserva el derecho de suspender o cancelar el Servicio en cualquier momento, 
a su entera discreción, con o sin previo aviso.</p>
<p>10/ <strong>Responsabilidad:</strong> En la medida máxima permitida por la ley, el Proveedor no será responsable de ningún daño directo, indirecto, incidental, especial, consecuente o ejemplar, incluyendo pero no limitado a daños por pérdida de beneficios, buena voluntad, uso, datos u otras pérdidas intangibles, resultantes del uso o la incapacidad para usar el Servicio.</p>
<p>11/ <strong>Jurisdicción y Ley Aplicable:</strong> Estas Condiciones de Uso se regirán e interpretarán de acuerdo con las leyes de España. Cualquier controversia que surja de estas Condiciones de Uso estará sujeta a la jurisdicción de los tribunales de España.</p>
<p>Por favor, recuerde que al utilizar el Servicio, usted acepta estas Condiciones de Uso. Si no está de acuerdo con alguna de estas condiciones, por favor, no utilice el Servicio.</p>
<p>Fecha de última actualización: 17/05/2023</p>
